---
title: Ошибка компилятора CS1017
ms.date: 07/20/2015
f1_keywords:
- CS1017
helpviewer_keywords:
- CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
ms.openlocfilehash: 03e4bbc41d0a103a1432906e77df4325f9a30e3f
ms.sourcegitcommit: 10986410e59ff29f2ec55c6759bde3eb4d1a00cb
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 05/31/2019
ms.locfileid: "66423140"
---
# <a name="compiler-error-cs1017"></a><span data-ttu-id="a48d6-102">Ошибка компилятора CS1017</span><span class="sxs-lookup"><span data-stu-id="a48d6-102">Compiler Error CS1017</span></span>
<span data-ttu-id="a48d6-103">Конструкции catch не могут использоваться после универсальной конструкции catch оператора try</span><span class="sxs-lookup"><span data-stu-id="a48d6-103">Catch clauses cannot follow the general catch clause of a try statement</span></span>  
  
 <span data-ttu-id="a48d6-104">Блок `catch` , не имеющий параметров, должен находиться в конце серии блоков `catch` .</span><span class="sxs-lookup"><span data-stu-id="a48d6-104">A `catch` block that does not take any parameters must be the last in a series of `catch` blocks.</span></span> <span data-ttu-id="a48d6-105">Дополнительные сведения об исключениях см. в разделе [исключения и обработка исключений](../../csharp/programming-guide/exceptions/index.md).</span><span class="sxs-lookup"><span data-stu-id="a48d6-105">For more information on exceptions, see [Exceptions and Exception Handling](../../csharp/programming-guide/exceptions/index.md).</span></span>  
  
## <a name="example"></a><span data-ttu-id="a48d6-106">Пример</span><span class="sxs-lookup"><span data-stu-id="a48d6-106">Example</span></span>  
 <span data-ttu-id="a48d6-107">Следующий пример приводит к возникновению ошибки CS1017:</span><span class="sxs-lookup"><span data-stu-id="a48d6-107">The following sample generates CS1017:</span></span>  
  
```csharp  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
