---
title: Операнд оператора Throw должен быть производным от System.Exception
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 92fccbd2faac5580d28fef8cc02b51b23715f136
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414950"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>Операнд оператора Throw должен быть производным от System.Exception
Аргумент для `Throw` должен быть либо экземпляром `System.Exception` , либо экземпляром класса, производного от `System.Exception`.  
  
 **Идентификатор ошибки:** BC30665  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
- Используйте аргумент, производный от `System.Exception`, как показано в приведенном ниже примере.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>См. также раздел

- [Оператор Throw](../language-reference/statements/throw-statement.md)
- [Оператор Try…Catch…Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Обработка и создание исключений в .NET](../../standard/exceptions/index.md)
