---
title: Предупреждение компилятора (уровень 1) CS1058
ms.date: 07/20/2015
f1_keywords:
- CS1058
helpviewer_keywords:
- CS1058
ms.assetid: ed50590c-f130-47c3-976d-322a6c8f996d
ms.openlocfilehash: ef7b2f774da9dd05425ff6ca01b04cb7dd16cb3d
ms.sourcegitcommit: 30a558d23e3ac5a52071121a52c305c85fe15726
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/25/2019
ms.locfileid: "75342466"
---
# <a name="compiler-warning-level-1-cs1058"></a>Предупреждение компилятора (уровень 1) CS1058
Предыдущее предложение catch уже перехватывает все исключения. Все возникшие необработанные исключения будут перенесены в System.Runtime.CompilerServices.RuntimeWrappedException  
  
 Этот атрибут приводит к возникновению ошибки CS1058, если для блока `catch()` не задан конкретный тип исключения после блока `catch (System.Exception e)`. Это предупреждение указывает на то, что блок `catch()` не будет перехватывать какие-либо исключения.  
  
Блок `catch()` после блока `catch (System.Exception e)` может перехватывать несовместимые с CLS исключения, если атрибуту `RuntimeCompatibilityAttribute` в файле AssemblyInfo.cs присвоено значение false: `[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = false)]`. Если этому атрибуту не присвоено явно значение false, все возникшие несовместимые с CLS исключения будут упаковываться как исключения и перехватываться блоком `catch (System.Exception e)`. Дополнительные сведения см. в статье [Практическое руководство. Перехват несовместимого с CLS исключения](../../programming-guide/exceptions/how-to-catch-a-non-cls-exception.md).
  
## <a name="example"></a>Пример  
 В следующем примере возникает ошибка CS1058.  
  
```csharp  
// CS1058.cs  
// CS1058 expected  
using System.Runtime.CompilerServices;  
  
// the following attribute is set to true by default in the C# compiler  
// set to false in your source code to resolve CS1058  
[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = true)]  
  
class TestClass   
{  
   static void Main()   
   {  
      try {}  
  
      catch (System.Exception e) {   
         System. Console.WriteLine("Caught exception {0}", e);  
      }  
  
      catch {}   // CS1058. This line will never be reached.  
   }  
}  
```
