---
title: Предупреждение компилятора (уровень 1) CS1058
ms.date: 07/20/2015
f1_keywords:
- CS1058
helpviewer_keywords:
- CS1058
ms.assetid: ed50590c-f130-47c3-976d-322a6c8f996d
ms.openlocfilehash: 6ef72ca103e6bc066aac76cc520ea160fdaa9caa
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/19/2019
ms.locfileid: "69603594"
---
# <a name="compiler-warning-level-1-cs1058"></a><span data-ttu-id="3c9a3-102">Предупреждение компилятора (уровень 1) CS1058</span><span class="sxs-lookup"><span data-stu-id="3c9a3-102">Compiler Warning (level 1) CS1058</span></span>
<span data-ttu-id="3c9a3-103">Предыдущее предложение catch уже перехватывает все исключения.</span><span class="sxs-lookup"><span data-stu-id="3c9a3-103">A previous catch clause already catches all exceptions.</span></span> <span data-ttu-id="3c9a3-104">Все возникшие необработанные исключения будут перенесены в System.Runtime.CompilerServices.RuntimeWrappedException</span><span class="sxs-lookup"><span data-stu-id="3c9a3-104">All exceptions thrown will be wrapped in a System.Runtime.CompilerServices.RuntimeWrappedException</span></span>  
  
 <span data-ttu-id="3c9a3-105">Этот атрибут приводит к возникновению ошибки CS1058, если для блока `catch()` не задан конкретный тип исключения после блока `catch (System.Exception e)`.</span><span class="sxs-lookup"><span data-stu-id="3c9a3-105">This attribute causes CS1058 if a `catch()` block has no specified exception type after a `catch (System.Exception e)` block.</span></span> <span data-ttu-id="3c9a3-106">Это предупреждение указывает на то, что блок `catch()` не будет перехватывать какие-либо исключения.</span><span class="sxs-lookup"><span data-stu-id="3c9a3-106">The warning advises that the `catch()` block will not catch any exceptions.</span></span>  
  
 <span data-ttu-id="3c9a3-107">Блок `catch()` после блока `catch (System.Exception e)` может перехватывать несовместимые с CLS исключения, если атрибуту `RuntimeCompatibilityAttribute` в файле AssemblyInfo.cs присвоено значение false: `[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = false)]`.</span><span class="sxs-lookup"><span data-stu-id="3c9a3-107">A `catch()` block after a `catch (System.Exception e)` block can catch non-CLS exceptions if the `RuntimeCompatibilityAttribute` is set to false in the AssemblyInfo.cs file: `[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = false)]`.</span></span> <span data-ttu-id="3c9a3-108">Если этому атрибуту не присвоено явно значение false, все возникшие несовместимые с CLS исключения будут упаковываться как исключения и перехватываться блоком `catch (System.Exception e)`.</span><span class="sxs-lookup"><span data-stu-id="3c9a3-108">If this attribute is not set explicitly to false, all thrown non-CLS exceptions are wrapped as Exceptions and the `catch (System.Exception e)` block catches them.</span></span> <span data-ttu-id="3c9a3-109">Дополнительные сведения см. в разделе [Практическое руководство. Перехват несовместимого с CLS исключения](../../programming-guide/exceptions/how-to-catch-a-non-cls-exception.md).</span><span class="sxs-lookup"><span data-stu-id="3c9a3-109">For more information, see [How to: Catch a non-CLS Exception](../../programming-guide/exceptions/how-to-catch-a-non-cls-exception.md).</span></span>  
  
## <a name="example"></a><span data-ttu-id="3c9a3-110">Пример</span><span class="sxs-lookup"><span data-stu-id="3c9a3-110">Example</span></span>  
 <span data-ttu-id="3c9a3-111">В следующем примере возникает ошибка CS1058.</span><span class="sxs-lookup"><span data-stu-id="3c9a3-111">The following example generates CS1058.</span></span>  
  
```csharp  
// CS1058.cs  
// CS1058 expected  
using System.Runtime.CompilerServices;  
  
// the following attribute is set to true by default in the C# compiler  
// set to false in your source code to resolve CS1058  
[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = true)]  
  
class TestClass   
{  
   static void Main()   
   {  
      try {}  
  
      catch (System.Exception e) {   
         System. Console.WriteLine("Caught exception {0}", e);  
      }  
  
      catch {}   // CS1058. This line will never be reached.  
   }  
}  
```
